### PR TITLE
Distinguishing Debian installation from Ubuntu one

### PR DESCRIPTION
**Pull request by romaindequidt**

### CODE REVIEW

**Comment by geerlingguy** [comment]
It looks like builds fail after this PR is applied due to a linting issue.

Can you provide any background on why this split would be necessary? The current tests seem to indicate it works fine across Debian and Ubuntu already.

**Comment by romaindequidt** [comment]
I'm going to check the linting issue.

FYI, [Debian install is pretty far from Ubuntu one](https://gluster.readthedocs.io/en/latest/Install-Guide/Install/) ;)
Furthermore, I wasn't able to use [module gluster_peer](https://docs.ansible.com/ansible/2.6/modules/gluster_peer_module.html), it was hanging doing "gluster pool list" with ubuntu version and is working with new debian one.

**Comment by romaindequidt** [comment]
@geerlingguy about the linting issue, my line is too long (more than the maximum: 120 chars) but the lint tool refuses multiple-line string.

> error    syntax error: expected <block end>, but found '<scalar>'

If you have any idea, do not hesitate

**Comment by romaindequidt** [comment]
Ok, it seems to be Ok now BTW

**Comment by romaindequidt** [comment]
@geerlingguy any estimated time of merge?

**Comment by geerlingguy** [comment]
Needs a passing test for debian9, so I'm going to add to PR and then if it passes I'll merge. Thanks!

**Pull request merged**
